### ISSUE TITLE
Urllib.unquote Won't work with Python 3

### ISSUE THREAD

**Issue by aa7955** [IBM-Cloud/sql-query-clients#5]
https://github.com/IBM-Cloud/sql-query-clients/blob/8947a6abb96cbc46e07e958067c41c8fed656e27/Python/ibmcloudsql/SQLQuery.py#L230

Same issue with urllib -> need `urllib.parse.unquote`

I'll see about making a pull request for this one.

**Comment by torsstei** [comment]
Just fixed and released 0.1.5. Thanks.

**Comment by aa7955** [comment]
Still getting an error with that. Is it possible that `urllib` is using `urllib3` instead? This is from DSX using Python 3.5:
```
--> 229         if sys.version_info >= (3, 0):
    230             print ("https://sql.ng.bluemix.net/sqlquery/?instance_crn={}".format(
    231                 urllib.parse.unquote(self.instance_crn)))

AttributeError: module 'urllib' has no attribute 'unquote'
```

**Comment by torsstei** [comment]
@aa7955 I think this was only due to an outdated ibmcloudsql in your notebook env. After updating to 0.1.5 the issue doesn't show up anymore.

**Comment by torsstei** [comment]
@aa7955 The issue is caused by DSX internally depending on tornado 4.5.2 and keeping it around even though you install 5.0. I've limited the prerequed version in setup.py now to 4.5.2 and now the problem is gone even when you install ibmcloudsql with --upgrade. Published as version 0.2.7.
